title: iTuna Documentation
author: Tobias Schmidt, Steffen Schneider

repository:
  url: https://github.com/dynamical-inference/ituna
  branch: main

exclude_patterns:
  - .github/*
  - slurm/*
  - third_party/*
  - _build/*

execute:
  execute_notebooks: "off"
  timeout: 300

sphinx:
  config:
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js
    nb_mime_priority_overrides: [
      ['html', 'application/vnd.plotly.v1+json', 10],
      ['html', 'text/html', 0]
    ]
